[package]
name = "parity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "bfi"
path = "bfi/main.rs"

[[bin]]
name = "arithpost"
path = "arithpost/main.rs"

[dependencies]
